### ISSUE TITLE
SB: The filter doesn't work for "Publisher Name" column (IE)

### ISSUE THREAD

**Issue by andrewkhomski** [andrewkhomski/SANDBOX-CPLplus-#5]
1) Navigate to this page
http://sandbox.cplplus.com/publishers
2) Enter any eligible value (ex: DTI) under the **Publisher Name** column
3) Observe it won't filter

**Comment by brendan-finmc** [comment]
fixed

**Comment by andrewkhomski** [comment]
Brendan - i still see the same issue. Did you commit?

![sb-issue-5](https://cloud.githubusercontent.com/assets/15894297/11800281/188af566-a2a9-11e5-8e20-8bf7cdf1cc2c.png)

**Comment by andrewkhomski** [comment]
This issue is now fixed and verified. Closing DF.
